### ISSUE TITLE
Looking for the solver

### ISSUE THREAD

**Issue by glaserL** [SergeyParamonov/sketching#1]
Hello,

thank you for your very interesting work this should help develop ASP programs very much! I am trying to use your work, but I am struggling to find the sketcher_sources/solver.py file that you point to. 

Could you help me find this?

Best regards
Luis

**Comment by SergeyParamonov** [comment]
Hey Luis,

I have uploaded the solver into the folder `solver/` it's messy since we thought of packaging into an open source project but it just never happened, so it's more like a bunch of my experimental scripts put together -- I am not even 100% it's the latest version, but it has been a while and I don't see any other code on my computer right now.

-- Sergey
